### ISSUE TITLE
Missing languages tracking issue

### ISSUE THREAD

**Issue by Richienb** [leachim6/hello-world#790]
The following languages are yet to be included:

- E100 Assembly
- A.NET
- A-0 System
- A+
- ABC ALGOL (extension of ABC)
- ACC
- Accent
- ACE DASL
- Action!
- Actor
- Adenine
- Agilent VEE
- Agora
- AIMMS
- Aldor
- Alef
- ALF
- ALGOL 58
- Alice
- Alma-0
- AmbientTalk
- AMPL
- Apache Pig latin
- App Inventor
- APT
- ARexx
- Argus
- Averest
- Axum
- Babbage
- Bertrand
- BLISS
- Blockly
- Boomerang
- Bytebytejump
- C--
- C/AL
- Cayenne
- Cecil
- Cesil
- Céu
- CFEngine
- Cg
- Charm
- CHILL
- CHIP-8
- chomski
- ChucK
- Cilk
- Citrine
- CL (IBM)
- Claire
- CLIST
- CLU
- CMS-2
- COMAL
- Combined Programming Language
- COMIT
- COMPASS
- Component Pascal
- Constraint Handling Rules
- COMTRAN
- Coq
- CorVision
- Cryptol
- Csound
- Curl
- Cybil
- Cyclone
- Cypher Query Language
- CEEMAC
- Darwin
- Datalog
- DATATRIEVE
- DinkC
- DIBOL
- DRAKON
- DYNAMO
- DAX
- E
- Ease
- Easy PL/I
- EASYTRIEVE PLUS
- Edinburgh IMP
- ELAN
- Epigram
- Easy Programming Language (EPL)
- Eltron Programming Language (EPL)
- es
- Escher
- ESPOL
- Esterel
- Etoys
- Euclid
- Euler
- EusLisp Robot Programming Language
- CMS EXEC
- EXEC 2
- Executable UML
- Ezhil
- Faust
- FFP
- FL
- Flavors
- Flex
- FlooP
- FLOW-MATIC
- FOCUS
- FOIL
- FORMAC
- \@Formula
- Fortress
- FP
- Franz Lisp
- Futhark
- F-Script
- Game Maker Language
- GameMonkey Script
- GAMS
- GAP
- GDL
- GEORGE
- GLSL
- GNU E
- GNU Guile
- Go!
- GOAL
- Gödel
- GOM
- GOTRAN
- GPSS
- GraphTalk
- GRASS
- Grasshopper
- HAGGIS
- HAL/S
- Halide
- Hamilton C shell
- Harbour
- Hartmann pipelines
- Hermes
- High Level Assembly
- HLSL
- Hollywood
- Hopscotch
- Hope
- Hugo
- Hume
- IBM Basic assembly language
- IBM HAScript
- IBM Informix-4GL
- IBM RPG
- J#
- J++
- JAL
- Janus (concurrent constraint programming language)
- Janus (time-reversible computing programming language)
- JASS
- JavaFX Script
- JCL
- JEAN
- Join Java
- JOSS
- Joule
- JOVIAL
- Joy
- JScript
- JScript .NET
- Kaleidoscope
- Karel
- KEE
- Kixtart
- Klerer-May System
- KIF
- Kojo
- KRC
- KRL
- KRL (KUKA Robot Language)
- KRYPTON
- Kom shell (ksh)
- Kodu
- Kv
- LabVIEW
- Ladder
- LANSA
- Lasso
- Lava
- LC-3
- Legoscript
- LIL
- Limnor
- LINC
- LINQ
- LIS
- LISA
- Language H
- Lite-C
- Lithe
- Little b
- LLL
- LPS
- LSE
- LiveCode
- Lucid
- Lustre
- LYaPAS
- Lynx
- M2001
- M#
- MAD (Michigan Algorithm Decoder)
- MAD/I
- Magik
- Magma
- Mani
- Maple
- MAPPER (BIS)
- MARK-IV (VISION:BUILDER)
- Mary
- MATH-MATIC
- Maude system
- Maxima
- Max
- Maya
- MDL
- Mesa
- MHEG-5
- Microcode
- Microscript
- MIIS
- Mirah
- Miranda
- MIVA Script
- ML
- Modula (Version 1)
- Mohol
- Mortran
- Mouse
- MPD
- MSL
- MuPAD
- Mutan
- Mystic Programming Language
- Napier88
- NESL
- Net.Data
- NetLogo
- NetRexx
- NewLISP
- NEWP
- Newspeak
- Nial
- Nickle
- Nix
- Not eXactly C
- Not Quite C
- NSIS
- Nu
- NXT-G
- Oak
- OBJ2
- Object Lisp
- ObjectLOGO
- Object Pascal
- Obliq
- occam
- occam-π
- OmniMark
- Opal
- OpenCL
- OpenEdge ABL
- OPL
- OpenVera
- OPS5
- OptimJ
- ORCA/Modula-2
- Oriel
- Orwell
- Oxygene
- P
- P4
- P"
- ParaSail
- PARI/GP
- Pascal Script (not Pascal)
- PCASTL
- PCF
- PEARL
- PDL
- Pico
- Picolisp
- Pict
- Pilot
- Pipelines
- PL-11
- PL/0
- PL/B
- PL/C
- PL/I
- PL/M
- PL/P
- PL/SQL
- PL360
- PLANC
- Plankalkül
- Planner
- PLEX
- PLEXIL
- Plus
- POP-11
- POP-2
- PortablE
- ROV-RAY SDL
- Powerhouse
- PowerBuilder
- PPL
- Prograph
- PROIV
- PROMAL
- PROSE modeling language
- PROTEL
- Pro*C
- Pure
- Qalb
- Quantum Computation Language
- QtScript
- QPL
- .QL
- R++
- RAPID
- Rapira
- Ratfiv
- rc
- Redcode
- Rlab
- ROOP
- RPL
- RSL
- S
- S2
- S3
- S-Lang
- S-PLUS
- SA-C
- SabreTalk
- SAIL
- SASL
- Sawzall
- Script.NET
- SenseTalk
- SequenceL
- Serpent
- SETL
- SIMPOL
- SIGNAL
- SiMPLE
- SIMSCRIPT
- Simulink
- Singularity
- SISAL
- SLIP
- SMALL
- Strongtalk
- Snap!
- SNOBOL
- Snowball
- SOL
- SOPHAEROS
- Source
- SPARK
- Speakeasy
- Sppedcode
- SPIN
- SPIR-V
- SP/k
- SPS
- SQR
- Squeak
- Squirrel
- SR
- S/SL
- Starlogo
- Strand
- Stata
- Stateflow
- Subtext
- SBL
- SuperTalk
- SYMPL
- SystemVerilog
- T
- TACL
- TACPOL
- TADS
- TAL
- Tea
- TECO
- TELCOMP
- TIE
- TMG
- Tom
- Toi
- Topspeed
- TPU
- Trac
- TTM
- T-SQL
- Transcript
- TTCN 1
- TTCN 2
- TUTOR
- TXL
- Tynker
- UCSD Pascal
- Umple
- Uniface
- UNITY
- Unreadable
- Viper
- Visual DataFlex
- Visual DialogScript
- Visual J++
- Visual LISP
- Visual Objects
- Visual Prolog
- VSXu
- WATFIV
- WebDNA
- Whiley
- Winbatch
- Wyvern
- X++
- X10
- XBL
- XC
- xHarbour
- Xojo
- XOTcl
- Xod
- XPL (not XPL0)
- XSB
- XSharp
- Xtend
- Yorick
- YQL
- Yoix
- YUI
- Z notation
- Z++
- Zebra
- Zeno
- ZetaLisp
- ZOPL

PRs are welcome!

## Useful sources

- [Wikipedia - List of programming languages](https://en.wikipedia.org/wiki/List_of_programming_languages)
- [Esolangs - Hello world program in esoteric languages](https://esolangs.org/wiki/Hello_world_program_in_esoteric_languages)
- [Rosetta Code - Hello World Text](https://rosettacode.org/wiki/Hello_world/Text)
- [The Hello World Collection](http://helloworldcollection.de)

**Comment by Explosion-Scratch** [comment]
You're missing Scratch 3.0.

**Comment by Richienb** [comment]
@Explosion-Scratch Already completed: https://github.com/leachim6/hello-world/blob/master/s/scratch.sb3

**Comment by nithinkodadhavadee** [comment]
# A
- [ ] 8051 Assembly
- [ ] A.NET
- [ ] E100 Assembly
- [ ] A-0 System
- [ ] A+
- [ ] ABC ALGOL (extension of ABC)
- [ ] ACC
- [ ] Accent
- [ ] ACE DASL
- [ ] Action!
- [ ] Actor
- [ ] Adenine
- [ ] Agil ent VEE
- [ ] Agora
- [ ] AIMMS
- [ ] Aldor
- [ ] Alef
- [ ] ALF
- [ ] ALGOL 58
- [ ] Alice
- [ ] Alma-0
- [ ] AmbientTalk
- [ ] AMPL
- [ ] Apache Pig latin
- [ ] App Inventor
- [ ] APT
- [ ] ARexx
- [ ] Argus
- [ ] AutoLISP
- [ ] Averest
- [ ] Axum
# B
- [ ] Babbage
- [ ] bc
- [ ] BeanShell
- [ ] Bertrand
- [ ] BLISS
- [ ] Blockly
- [ ] Boomerang
- [ ] Bytebytejump
# C
- [ ] C--
- [ ] C*
- [ ] C/AL
- [ ] Caché ObjectScript
- [ ] Cayenne
- [ ] Cecil
- [ ] Cesil
- [ ] Céu
- [ ] CFEngine
- [ ] Cg
- [ ] Charm
- [ ] CHILL
- [ ] CHIP-8
- [ ] chomski
- [ ] ChucK
- [ ] Cilk
- [ ] Citrine
- [ ] CL (IBM)
- [ ] Claire
- [ ] CLIST
- [ ] CLU
- [ ] CMS-2
- [ ] CobolScript
- [ ] COMAL
- [ ] Combined Programming Language
- [ ] COMIT
- [ ] Common Intermediate Language
- [ ] COMPASS
- [ ] Component Pascal
- [ ] Constraint Handling Rules
- [ ] COMTRAN
- [ ] Coq
- [ ] Coral 66
- [ ] CorVision
- [ ] Cryptol
- [ ] Csound
- [ ] Curl
- [ ] Cybil
- [ ] Cyclone
- [ ] Cypher Query Language
- [ ] CEEMAC
# D
- [ ] Darwin
- [ ] DataFlex
- [ ] Datalog
- [ ] DATATRIEVE
- [ ] dBase
- [ ] DinkC
- [ ] DIBOL
- [ ] Dog
- [ ] DRAKON
- [ ] DYNAMO
- [ ] DAX
# E
- [ ] E
- [ ] Ease
- [ ] Easy PL/I
- [ ] EASYTRIEVE PLUS
- [ ] Edinburgh IMP
- [ ] ELAN
- [ ] Emerald
- [ ] Epigram
- [ ] Easy Programming Language (EPL)
- [ ] Eltron Programming Language (EPL)
- [ ] es
- [ ] Escher
- [ ] ESPOL
- [ ] Esterel
- [ ] Etoys
- [ ] Euclid
- [ ] Euler
- [ ] EusLisp Robot Programming Language
- [ ] CMS EXEC
- [ ] EXEC 2
- [ ] Executable UML
- [ ] Ezhil
# F
- [ ] F
- [ ] Faust
- [ ] FFP
- [ ] FL
- [ ] Flavors
- [ ] Flex
- [ ] FlooP
- [ ] FLOW-MATIC
- [ ] FOCUS
- [ ] FOIL
- [ ] FORMAC
- [ ] @formula
- [ ] Fortress
- [ ] FP
- [ ] Franz Lisp
- [ ] Futhark
- [ ] F-Script
# G
- [ ] Game Maker Language
- [ ] GameMonkey Script
- [ ] GAMS
- [ ] GAP
- [ ] Genie
- [ ] GDL
- [ ] GEORGE
- [ ] GLSL
- [ ] GNU E
- [ ] GNU Guile
- [ ] Go!
- [ ] GOAL
- [ ] Gödel
- [ ] GOM
- [ ] GOTRAN
- [ ] GPSS
- [ ] GraphTalk
- [ ] GRASS
- [ ] Grasshopper
# H
- [ ] HAGGIS
- [ ] HAL/S
- [ ] Halide
- [ ] Hamilton C shell
- [ ] Harbour
- [ ] Hartmann pipelines
- [ ] Hermes
- [ ] High Level Assembly
- [ ] HLSL
- [ ] Hollywood
- [ ] Hopscotch
- [ ] Hope
- [ ] Hugo
- [ ] Hume
# I
- [ ] IBM Basic assembly language
- [ ] IBM HAScript
- [ ] IBM Informix-4GL
- [ ] IBM RPG
# J
- [ ] J#
- [ ] J++
- [ ] JAL
- [ ] Janus (concurrent constraint programming language)
- [ ] Janus (time-reversible computing programming language)
- [ ] JASS
- [ ] JavaFX Script
- [ ] JCL
- [ ] JEAN
- [ ] Join Java
- [ ] JOSS
- [ ] Joule
- [ ] JOVIAL
- [ ] Joy
- [ ] JScript
- [ ] JScript .NET
# K
- [ ] Kaleidoscope
- [ ] Karel
- [ ] KEE
- [ ] Kixtart
- [ ] Klerer-May System
- [ ] KIF
- [ ] Kojo
- [ ] KRC
- [ ] KRL
- [ ] KRL (KUKA Robot Language)
- [ ] KRYPTON
- [ ] Kom shell (ksh)
- [ ] Kodu
- [ ] Kv
# L
- [ ] LabVIEW
- [ ] Ladder
- [ ] LANSA
- [ ] Lasso
- [ ] Lava
- [ ] LC-3
- [ ] Legoscript
- [ ] LIL
- [ ] LilyPond
- [ ] Limnor
- [ ] LINC
- [ ] LINQ
- [ ] LIS
- [ ] LISA
- [ ] Language H
- [ ] Lite-C
- [ ] Lithe
- [ ] Little b
- [ ] LLL
- [ ] LPS
- [ ] LSE
- [ ] LiveCode
- [ ] Lucid
- [ ] Lustre
- [ ] LYaPAS
- [ ] Lynx
# M
- [ ] M2001
- [ ] M#
- [ ] MAD (Michigan Algorithm Decoder)
- [ ] MAD/I
- [ ] Magik
- [ ] Magma
- [ ] Mani
- [ ] Maple
- [ ] MAPPER (BIS)
- [ ] MARK-IV (VISION:BUILDER)
- [ ] Mary
- [ ] MATH-MATIC
- [ ] Maude system
- [ ] Maxima
- [ ] Max
- [ ] Maya
- [ ] MDL
- [ ] Mesa
- [ ] MHEG-5
- [ ] Microcode
- [ ] Microscript
- [ ] MIIS
- [ ] Mirah
- [ ] Miranda
- [ ] MIVA Script
- [ ] ML
- [ ] Modula (Version 1)
- [ ] Mohol
- [ ] Mortran
- [ ] Mouse
- [ ] MPD
- [ ] MSL
- [ ] MuPAD
- [ ] Mutan
- [ ] Mystic Programming Language
# N
- [ ] Napier88
- [ ] NESL
- [ ] Net.Data
- [ ] NetLogo
- [ ] NetRexx
- [ ] NewLISP
- [ ] NEWP
- [ ] Newspeak
- [ ] Nial
- [ ] Nickle
- [ ] Nix
- [ ] Not eXactly C
- [ ] Not Quite C
- [ ] NSIS
- [ ] Nu
- [ ] NXT-G
# O
- [ ] o:XML
- [ ] Oak
- [ ] OBJ2
- [ ] Object Lisp
- [ ] ObjectLOGO
- [ ] Object Pascal
- [ ] Obliq
- [ ] occam
- [ ] occam-π
- [ ] Octave
- [ ] OmniMark
- [ ] Opal
- [ ] OpenCL
- [ ] OpenEdge ABL
- [ ] OPL
- [ ] OpenVera
- [ ] OPS5
- [ ] OptimJ
- [ ] ORCA/Modula-2
- [ ] Oriel
- [ ] Orwell
- [ ] Oxygene
# P
- [ ] P
- [ ] P4
- [ ] P"
- [ ] ParaSail
- [ ] PARI/GP
- [ ] Pascal Script (not Pascal)
- [ ] PCASTL
- [ ] PCF
- [ ] PEARL
- [ ] PeopleCode
- [ ] PDL
- [ ] Pico
- [ ] Picolisp
- [ ] Pict
- [ ] Pilot
- [ ] Pipelines
- [ ] PL-11
- [ ] PL/0
- [ ] PL/B
- [ ] PL/C
- [ ] PL/I
- [ ] PL/M
- [ ] PL/P
- [ ] PL/SQL
- [ ] PL360
- [ ] PLANC
- [ ] Plankalkül
- [ ] Planner
- [ ] PLEX
- [ ] PLEXIL
- [ ] Plus
- [ ] POP-11
- [ ] POP-2
- [ ] PortablE
- [ ] ROV-RAY SDL
- [ ] Powerhouse
- [ ] PowerBuilder
- [ ] PPL
- [ ] Prograph
- [ ] PROIV
- [ ] PROMAL
- [ ] PROSE modeling language
- [ ] PROTEL
- [ ] Pro*C
- [ ] Pure
# Q
- [ ] Qalb
- [ ] Quantum Computation Language
- [ ] QtScript
- [ ] QPL
- [ ] .QL
# R
- [ ] R++
- [ ] Raku
- [ ] RAPID
- [ ] Rapira
- [ ] Ratfiv
- [ ] rc
- [ ] Redcode
- [ ] Rlab
- [ ] ROOP
- [ ] RPL
- [ ] RSL
# S
- [ ] S
- [ ] S2
- [ ] S3
- [ ] S-Lang
- [ ] S-PLUS
- [ ] SA-C
- [ ] SabreTalk
- [ ] SAIL
- [ ] SASL
- [ ] Sawzall
- [ ] Script.NET
- [ ] SenseTalk
- [ ] SequenceL
- [ ] Serpent
- [ ] SETL
- [ ] SIMPOL
- [ ] SIGNAL
- [ ] SiMPLE
- [ ] SIMSCRIPT
- [ ] Simulink
- [ ] Singularity
- [ ] SISAL
- [ ] SLIP
- [ ] SMALL
- [ ] Strongtalk
- [ ] Snap!
- [ ] SNOBOL
- [ ] Snowball
- [ ] SOL
- [ ] SOPHAEROS
- [ ] Source
- [ ] SPARK
- [ ] Speakeasy
- [ ] Sppedcode
- [ ] SPIN
- [ ] SPIR-V
- [ ] SP/k
- [ ] SPS
- [ ] SQR
- [ ] Squeak
- [ ] Squirrel
- [ ] SR
- [ ] S/SL
- [ ] Starlogo
- [ ] Strand
- [ ] Stata
- [ ] Stateflow
- [ ] Subtext
- [ ] SBL
- [ ] SuperTalk
- [ ] SYMPL
- [ ] SystemVerilog
# T
- [ ] T
- [ ] TACL
- [ ] TACPOL
- [ ] TADS
- [ ] TAL
- [ ] Tea
- [ ] TECO
- [ ] TELCOMP
- [ ] TIE
- [ ] TMG
- [ ] Tom
- [ ] Toi
- [ ] Topspeed
- [ ] TPU
- [ ] Trac
- [ ] TTM
- [ ] T-SQL
- [ ] Transcript
- [ ] TTCN 1
- [ ] TTCN 2
- [ ] TUTOR
- [ ] TXL
- [ ] Tynker
# U
- [ ] UCSD Pascal
- [ ] Umple
- [ ] Unicon
- [ ] Uniface
- [ ] UNITY
- [ ] Unreadable
- [ ] UnrealScript
# V
- [ ] Viper
- [ ] Visual DataFlex
- [ ] Visual DialogScript
- [ ] Visual J++
- [ ] Visual LISP
- [ ] Visual Objects
- [ ] Visual Prolog
- [ ] VSXu
# W
- [ ] WATFIV
- [ ] WebDNA
- [ ] Whiley
- [ ] Winbatch
- [ ] Wyvern
# X
- [ ] X++
- [ ] X10
- [ ] XBL
- [ ] XC
- [ ] xHarbour
- [ ] Xojo
- [ ] XOTcl
- [ ] Xod
- [ ] XPL (not XPL0)
- [ ] XSB
- [ ] XSharp
- [ ] Xtend
# Y
- [ ] Yorick
- [ ] YQL
- [ ] Yoix
- [ ] YUI
# Z
- [ ] Z notation
- [ ] Z++
- [ ] Zebra
- [ ] Zeno
- [ ] ZetaLisp
- [ ] ZOPL
- [ ] ZPL
- [ ] ZScript

**Comment by MrBrain295** [comment]
Is this tracker up to date?

**Comment by Richienb** [comment]
Just updated it.

**Comment by MrBrain295** [comment]
ZPL is in the repository

**Comment by MrBrain295** [comment]
Common Intermediate language is all ready done just shortened to CIL.

**Comment by Richienb** [comment]
Thanks for noticing! Updated.

**Comment by MrBrain295** [comment]
C* is [here](http://helloworldcollection.de/#C*)

**Comment by MrBrain295** [comment]
I already added C*

**Comment by MrBrain295** [comment]
I added autolusp

**Comment by MrBrain295** [comment]
@Richienb how did you find all these languages most I can’t find anywhere?

**Comment by MrBrain295** [comment]
like c-- or bytebyte jump

**Comment by Richienb** [comment]
> how did you find all these languages

https://en.wikipedia.org/wiki/List_of_programming_languages

**Comment by MrBrain295** [comment]
I did PeopleCode

**Comment by MrBrain295** [comment]
I added Dog

**Comment by MrBrain295** [comment]
I added o:XML

**Comment by MrBrain295** [comment]
Not eXactly C requires 2 files so should I make a folder inside "n" to do this? @Richienb

**Comment by MrBrain295** [comment]
@Richienb LillyPond is done

**Comment by MrBrain295** [comment]
i get mine from https://github.com/knightking100/hello-worlds/blob/master/LANGUAGES.md

**Comment by abt8601** [comment]
> - Octave

Octave has been done in #794.

**Comment by MrBrain295** [comment]
> I added o:XML

**Comment by MrBrain295** [comment]
@Richienb [φ](https://esolangs.org/wiki/%CE%A6) is missing

**Comment by Potherca** [comment]
I haven't gotten around to automating things yet, and the current version is a couple of years out of date, but would something like this: https://blog.pother.ca/hello-world-cross-reference/ be useful? (I was planning on improving it this holiday anyway...)

**Comment by MrBrain295** [comment]
Wow, I’ll look into it.

**Comment by Richienb** [comment]
> Not eXactly C requires 2 files

Sorry for the late response - I would go with a folder.

**Comment by Potherca** [comment]
@MrBrain295 The idea was to create a list of which project has which language and then exchange "Hello World" solutions between projects for those that are missing (to prevent duplicate work). Because of personal circumstances (and then COVID) I've not had time to revisit the project, but it is very much at the top of the list for my hobby projects this Xmas.

**Comment by Tyler887** [comment]
You forgot [fancade](https://facade.com)

**Comment by MrBrain295** [comment]
Moved to the wiki section.

**Comment by calgary34** [comment]
This issue can now be unpinned.
